name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file ./SpringBootVzpostavitev/pom.xml
      
    - name: Run tests with H2 database
      run: mvn test
      env:
        SPRING_DATASOURCE_URL: jdbc:h2:mem:testdb
        SPRING_DATASOURCE_USERNAME: sa
        SPRING_DATASOURCE_PASSWORD: ""
        SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.h2.Driver
        SPRING_JPA_SHOW_SQL: "true"
        SPRING_JPA_GENERATE_DDL: "true"
        SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.H2Dialect
        SERVER_PORT: 8080
        SERVER_SERVLET_CONTEXT_PATH: /api/v1

        SPRING_MAIL_HOST: smtp.gmail.com
        SPRING_MAIL_PORT: 587
        SPRING_MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}        # Add in GitHub Secrets
        SPRING_MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}        # Add in GitHub Secrets
        SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
        SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"
        SPRING_MAIL_PROPERTIES_MAIL_DEBUG: "true"

    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
