name: Java CI and SonarQube

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: auxilium
          MYSQL_USER: admin
          MYSQL_PASSWORD: admin
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Wait for MySQL
        run: |
          until mysqladmin ping -h127.0.0.1 -uadmin -padmin --silent; do
            echo "Waiting for database connection..."
            sleep 2
          done

      - name: Build with Maven
        run: mvn -f SpringBootVzpostavitev/pom.xml clean install

      - name: Run tests with Maven
        run: mvn -f SpringBootVzpostavitev/pom.xml test

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        with:
          args: >
            -Dsonar.java.binaries=SpringBootVzpostavitev/target/classes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
